mun/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views as index

urlpatterns = [
    path('', index.index),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('users/', include('users.urls')),
    path('delegation/', include('delegation.urls')),
    path('chair/', include('chair.urls')),
    path('secretariat/', include('secretariat.urls')),
    path('tinymce/', include('tinymce.urls')),
]

secretariat/urls.py
from . import views
from django.urls import path, include

app_name = 'secretariat'

urlpatterns = [
        path('', views.index, name='index'),
        path('add_chair/', views.add_chair, name='add_chair'),
        path('progress/', views.progress, name='progress'),
        path('progress/<slug>/', views.progress_sheet, name='progress_sheet'),
        path('requests/', views.requests, name='requests'),
        path('requests/change_status/<request_key>/', views.change_status, name='change_status'),
        path('allocations/', views.allocations, name='allocations'),
        path('allocations/add_del/', views.add_allocation_delegate, name='add_allocation_delegate'),
        path('allocations/delete_del/', views.delete_allocation_delegate, name='delete_allocation_delegate'),
]

secretariat/models.py
from django.db import models
from django.utils import timezone
from delegation.models import Committee
from users.models import User
from tinymce import HTMLField

# Create your models here.


class Chair(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    committee = models.ForeignKey(
        Committee, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return f"Chair: {self.user} - {self.committee}"


class ProgressSheet(models.Model):

    committee = models.OneToOneField(Committee, on_delete=models.CASCADE)

    data = HTMLField(blank=True, null=True)

    def __str__(self):
        return f"Progress Sheet: {self.committee}"


class LogisticsRequest(models.Model):

    committee = models.ForeignKey(Committee, on_delete=models.CASCADE)

    description = models.CharField(max_length=200)
    timestamp = models.DateTimeField('timestamp', auto_now_add=True)
    completed = models.BooleanField(default=False)

    def __str__(self):
        return f"Request: {self.committee} - {self.timestamp}"

secretariat/forms.py
from django import forms
from django.db import models
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from tinymce.widgets import TinyMCE

from users.models import User
from delegation.models import Committee, Allocation, Country, Committee
from .models import Chair, LogisticsRequest, ProgressSheet


class ChairCreationForm(UserCreationForm):

    email = forms.EmailField(required=True)
    committee = forms.ModelChoiceField(
        queryset=Committee.objects.all(), required=True)

    class Meta(UserCreationForm.Meta):

        model = User
        fields = ['username', 'email', 'password1', 'password2', 'committee']

    def save(self, commit=True):
        user = super().save(commit=False)
        user.email = self.cleaned_data["email"]
        user.is_chair = True
        if commit:
            user.save()
            chair = Chair.objects.create(
                user=user, committee=self.cleaned_data['committee'])
        return user


class ProgressSheetForm(forms.ModelForm):

    data = forms.CharField(widget=TinyMCE(attrs={'cols': 50, 'rows': 30}))

    class Meta:
        model = ProgressSheet
        fields = ['data', ]


class LogisticsRequestForm(forms.ModelForm):

    class Meta:
        model = LogisticsRequest
        fields = ['description', ]


class CountryForm(forms.ModelForm):
    class Meta:
        model = Country
        fields = ['name', ]


class CommitteeForm(forms.ModelForm):
    class Meta:
        model = Committee
        fields = '__all__'


class AllocationForm(forms.ModelForm):
    class Meta:
        model = Allocation
        fields = ['country', ]

secretariat/views.py
from django.shortcuts import render, redirect, HttpResponse
from django.contrib import messages
from django.http import JsonResponse
from django.core.exceptions import ObjectDoesNotExist

from .forms import ChairCreationForm, AllocationForm, CountryForm, CommitteeForm
from .models import ProgressSheet, LogisticsRequest
from delegation.models import Delegate, Allocation, Committee, Country
from .filters import RequestFilter, DelegateFilter, AllocationFilter

# Create your views here.


def index(request):
    TITLE = "Home"
    if request.user.is_authenticated:
        if request.user.is_secretariat:

            pages = {
                "Add Chair": "add_chair/",
                "Allocations": "allocations/",
                "Progress Sheets": "progress/",
                "Logistics Requests": "requests/",
            }

            return render(request,
                          "secretariat/index.html",
                          {"title": TITLE,
                          "tenant": request.tenant,
                          "pages": pages})

    messages.error(request, "You are not authorized to access that page")
    return redirect('users:index')


def allocations(request):
    TITLE = "Allocations"
    if request.user.is_authenticated:
        if request.user.is_secretariat:

            #Create filters for allocations and delegates
            delegates = Delegate.objects.all().order_by('-past_conferences')
            delegate_filter = DelegateFilter(request.GET, queryset=delegates)
            allocations = Allocation.objects.all()
            allocation_filter = AllocationFilter(
                request.GET, queryset=allocations)
            no_committee_selected = True

            #Check whether committee filter is selected
            if request.GET and 'committee' in request.GET:
                if request.GET['committee']:
                    #If no committee is selected, do not render allocations
                    no_committee_selected = False

            return render(request,
                          "secretariat/allocations.html",
                          {
                              "title": TITLE,
                              "tenant": request.tenant,
                              'delegate_filter': delegate_filter,
                              'allocation_filter': allocation_filter,
                              'no_committee_selected': no_committee_selected,
                          }
                          )

    messages.error(request, "You are not authorized to access that page")
    return redirect('users:index')


def add_allocation_delegate(request):

    if request.method == "POST":
        #Get IDs from post
        delegateID = request.POST['delegateID']
        allocationID = request.POST['allocationID']

        try:
            #Link objects together
            delegate = Delegate.objects.get(pk=delegateID)
            allocation = Allocation.objects.get(pk=allocationID)
            allocation.delegate = delegate
            allocation.save()
            response = {
                'status': 1,
            }
            messages.info(request, "Delegate allocated")

        except Exception as e:
            response = {
                'status': 0,
            }

        return JsonResponse(response)


def delete_allocation_delegate(request):

    if request.method == "POST":
        delegateID = request.POST['delegateID']

        try:
            allocation = Allocation.objects.get(delegate__pk=delegateID)
            allocation.delegate = None
            allocation.save()
            response = {
                'status': 1,
            }
            messages.info(request, "Delegate removed")

        except Exception as e:
            response = {
                'status': 0,
            }

        return JsonResponse(response)


def add_chair(request):
    TITLE = "Add Chair Account"
    if request.user.is_authenticated:
        if request.user.is_secretariat:

            #Create Chair account
            if request.method == "POST":
                form = ChairCreationForm(request.POST)
                if form.is_valid():
                    user = form.save()
                    username = form.cleaned_data.get('username')
                    messages.success(
                        request, f"You have successfully created a chair account: {username}")

                else:
                    for field in form:
                        for error in field.errors:
                            messages.error(request, error)

                    return render(request=request,
                                  template_name="secretariat/add_chair.html",
                                  context={"title": TITLE,
                                           "tenant": request.tenant,
                                           "form": form})

            form = ChairCreationForm
            return render(request,
                          "secretariat/add_chair.html",
                          {"title": TITLE,
                          "tenant": request.tenant,
                           "form": form}
                          )

    messages.error(request, "You are not authorized to access that page")
    return redirect('users:index')


def progress(request):
    TITLE = "Progress Sheets"
    if request.user.is_authenticated:
        if request.user.is_secretariat:

            #Create progress sheet for committees without progress sheets
            committees = Committee.objects.all()
            for committee in committees:
                try:
                    committee.progresssheet
                except ObjectDoesNotExist:
                    #If committee has no progress sheet, create it
                    new_sheet = ProgressSheet(committee=committee)
                    new_sheet.save()

            sheets = ProgressSheet.objects.all()
            return render(request,
                          "secretariat/progress.html",
                          {"title": TITLE,
                          "tenant": request.tenant,
                           "sheets": sheets})

    messages.error(request, "You are not authorized to access that page")
    return redirect('users:index')


def progress_sheet(request, slug):
    TITLE = "Progress Sheet"
    if request.user.is_authenticated:
        if request.user.is_secretariat:

            try:
                #Get sheet being rendered and get others
                sheet = ProgressSheet.objects.get(committee__name=slug)
                other_sheets = ProgressSheet.objects.exclude(
                    committee=sheet.committee)
            except ObjectDoesNotExist:
                messages.error(request, "That sheet does not exist")
                return redirect('users:index')

            return render(request,
                          "secretariat/progress_sheet.html",
                          {"title": TITLE,
                          "tenant": request.tenant,
                           "sheet": sheet,
                           "other_sheets": other_sheets})

    messages.error(request, "You are not authorized to access that page")
    return redirect('users:index')


def requests(request):
    TITLE = "Requests"
    if request.user.is_authenticated:
        if request.user.is_secretariat:

            #Create request filter
            request_list = LogisticsRequest.objects.all().order_by('-timestamp')
            request_filter = RequestFilter(request.GET, queryset=request_list)

            return render(request,
                          "secretariat/requests.html",
                          {"title": TITLE,
                          "tenant": request.tenant,
                           'requests': request_list,
                           'filter': request_filter})

    messages.error(request, "You are not authorized to access that page")
    return redirect('users:index')


def change_status(request, request_key):
    if request.user.is_authenticated:
        if request.user.is_secretariat:

            #Get request object
            logistics_request = LogisticsRequest.objects.get(pk=request_key)
            #Flip boolean value
            logistics_request.completed = not logistics_request.completed
            logistics_request.save()
            if logistics_request.completed:
                messages.info(request, "Request marked as completed")
            else:
                messages.info(request, "Request marked as incomplete")

            return redirect('secretariat:requests')

    messages.error(request, "You are not authorized to access that page")
    return redirect('users:index')

secretariat/templates/secretariat/add_chair.html
{% extends 'header.html' %}

{% block content %}

<form method="POST">
  {% csrf_token %}
  {{form.as_p}}
  <button type="submit" class="btn cyan darken-1">Add Chair Account</button>
</form>

{% endblock %}

secretariat/templates/secretariat/allocations.html
{% extends 'header.html' %}

{% block content %}
<style>
  .delete {
    display: inline-block;
    float: right;
    margin: 5px 5px 0 0;
    position: absolute;
    top: 0;
    right: 0;
  }
</style>
<script>
  function delete_delegate(delegateID) {
    $.post(
      "{% url 'secretariat:delete_allocation_delegate' %}", {
        csrfmiddlewaretoken: '{{ csrf_token }}',
        delegateID: delegateID,
      },
      function(data) {
        if (data.status == 1) {
          location.reload();
        } else {

        }
      });
  }

  function allowDrop(ev) {
    ev.preventDefault();
  }

  function drag(ev) {
    ev.dataTransfer.setData("text", ev.target.id);
  }

  function drop(ev) {
    ev.preventDefault();
    var data = ev.dataTransfer.getData("text");
    var allocationID = ev.target.id;
    var delegateID = document.getElementById(data).id;
    var allocationID = allocationID.slice(11);
    var delegateID = delegateID.slice(9);

    $.post("{% url 'secretariat:add_allocation_delegate' %}", {
        csrfmiddlewaretoken: '{{ csrf_token }}',
        delegateID: delegateID,
        allocationID: allocationID
      },
      function(data) {
        if (data.status == 1) {
          location.reload();
        } else {
          location.reload();
        }
      });
  }
</script>
<div class="row">
  <form method="get">
    <div class="col s6">

      <p>
        <label for="{{ delegate_filter.form.delegation.id_for_label }}">
          {{ delegate_filter.form.delegation.label }}:
        </label>
        {{ delegate_filter.form.delegation }}
      </p>

      <div class="row">
        <div class="col s6">
          <p>
            <label for="{{ delegate_filter.form.committee_preference.id_for_label }}">
              {{ delegate_filter.form.committee_preference.label }}:
            </label>
            {{ delegate_filter.form.committee_preference }}
          </p>
        </div>
        <div class="col s6">
          <p>
            <label for="{{ delegate_filter.form.country_preference.id_for_label }}">
              {{ delegate_filter.form.country_preference.label }}:
            </label>
            {{ delegate_filter.form.country_preference }}
          </p>
        </div>
      </div>
      <button class="btn" type="submit">Search</button>

    </div>

    <div class="col s6">
      {{ allocation_filter.form.as_p }}
      <button class="btn" type="submit">Select</button>
    </div>

  </form>
</div>

<div class="row">
  <div class="col s4">
    <div class="row" style="height:400px;overflow:auto">
      {% for del in delegate_filter.qs %}
      {% if not del.allocation %}
      <div class="card blue-grey darken-1" draggable="true" ondragstart="drag(event)" id="delegate-{{del.pk}}">
        <div class="card-content white-text">
          <p class="card-title">{{ del.first_name }} {{ del.last_name }}</p>
          <p style="font-size:90%">{{ del.delegation }}</p>
          <p style="font-size:70%">{{ del.past_conferences }} Conferences</p>
          <p style="font-size:70%">{{ del.committee_preference }}</p>
          <p style="font-size:70%">{{ del.country_preference }}</p>
        </div>
      </div>
      {% endif %}
      {% endfor %}
    </div>
  </div>

  <div class="col s6 push-s2">
    <div class="row" style="height:400px;overflow:auto">
      {% if not no_committee_selected %}
      <table class="centered">
        <thead>
          <tr>
            <th>Country</th>
            <th>Delegate</th>
          </tr>
        </thead>
        <tbody>
          {% for allocation in allocation_filter.qs %}
          <tr>
            <td>{{ allocation.country }}</td>
            <td>
              {% if allocation.delegate %}
              <div style="height:120px;" class="card blue-grey darken-1" id="delegate-{{allocation.delegate.pk}}">
                <div class="card-content white-text">
                  <p class="card-title">{{ allocation.delegate.first_name }} {{ allocation.delegate.last_name }}</p>
                  <p style="font-size:90%">{{ allocation.delegate.delegation }}</p>
                  <p style="font-size:70%">{{ allocation.delegate.past_conferences }} Conferences</p>
                  <button class="btn-flat delete" style='color:white;' id="{{ allocation.delegate.pk }}" onclick="delete_delegate(this.id)">
                    <i class="small material-icons">clear</i>
                  </button>
                </div>
              </div>
              {% else %}
              <div style="height:120px;" id="allocation-{{ allocation.pk }}" ondrop="drop(event)" ondragover="allowDrop(event)"></div>
              {% endif %}
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
      {% else %}
      <h5>Please select a committee</h5>
      {% endif %}
    </div>
  </div>
</div>

{% endblock %}

secretariat/templates/secretariat/index.html
{% extends 'header.html' %}

{% block content %}
<div class="row">
  {% for name, url in pages.items %}
  <div class="col s12 m12 l6">
    <div class="card red accent-4 hoverable">
      <div class="card-content white-text">
        <span class="card-title">{{name}}</span>
      </div>
      <div class="card-action">
        <a href="{{url}}">Open</a>
      </div>
    </div>
  </div>
  {% endfor %}
</div>
{% endblock %}

secretariat/templates/secretariat/progress.html
{% extends "header.html" %}

{% block content %}

<div class="row">
  {% for sheet in sheets %}
  <div class="col s12 m6 l4">
    <div class="card red accent-4 hoverable">
      <div class="card-content white-text">
        <span class="card-title">{{sheet.committee}}</span>
      </div>
      <div class="card-action">
        <a href="{{sheet.committee}}">Open</a>
      </div>
    </div>
  </div>
  {% endfor %}
</div>

{% endblock %}

secretariat/templates/secretariat/progress_sheet.html
{% extends "header.html" %}

{% block content %}

<div class="row">
  <div class="col s12 m8 l8 brown lighten-5">
    <h3 class="center-align">{{sheet.committee}} Progress Sheet</h3>
    <br>
    <p class="">{{sheet.data|safe}}</p>
  </div>
  <div class="col s12 m4 l4">
    <ul class="collapsible popout">
      <li class="active">
        <div class="collapsible-header">{{sheet.committee}}<br>(currently viewing)</div>
      </li>
      {% for other_sheet in other_sheets %}
      <li>
        <div class="collapsible-header">{{other_sheet.committee}}</div>
        <div class="collapsible-body">
          <p>
            <a href="/secretariat/progress/{{other_sheet.committee}}">
              <button class="btn waves-effect waves-light right-align" style="background-color:yellow; color:black">Go</button>
            </a>
          </p>
        </div>
      </li>
      {% endfor %}
    </ul>
  </div>
</div>

{% endblock %}

secretariat/templates/secretariat/requests.html
{% extends 'header.html' %}

{% block content %}
<div class="row">
  <form method="get">
    {{ filter.form.as_p }}
    <button class="btn" type="submit">Search</button>
  </form>
</div>
<div class="row">
  <table class="highlight responsive-table centered">
    <thead>
      <tr>
        <th>ID</th>
        <th>Committee</th>
        <th>Description</th>
        <th>Timestamp</th>
        <th>Completion Status</th>
      </tr>
    </thead>

    <tbody>
      {% for request in filter.qs %}
      <tr>
        <td>{{request.pk}}</td>
        <td>{{request.committee}}</td>
        <td>{{request.description}}</td>
        <td>{{request.timestamp}}</td>
        <td>
          <a href="change_status/{{request.pk}}">
            {% if request.completed == True %}
            <button class="btn-floating green darken-1">
              <i class="small material-icons">check</i>
            </button>
            {% else %}
            <button class="btn-floating red darken-1">
              <i class="small material-icons">clear</i>
            </button>
            {% endif %}
          </a>
        </td>

      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>


{% endblock %}