mun/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views as index

urlpatterns = [
    path('', index.index),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('users/', include('users.urls')),
    path('delegation/', include('delegation.urls')),
    path('chair/', include('chair.urls')),
    path('secretariat/', include('secretariat.urls')),
    path('tinymce/', include('tinymce.urls')),
]

users/urls.py
from . import views
from django.urls import path, include
from django.contrib.auth import views as auth_views

app_name = 'users'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('logout/', views.logout_request, name='logout'),
    path('index/', views.index, name='index'),
    path('', views.home, name='home'),
    path('login/', views.login_request, name="login"),
    path('account/', views.account, name="account"),

    path('password/', auth_views.PasswordChangeView.as_view()),
    path('password/done/', auth_views.PasswordChangeDoneView.as_view(), name="password_change_done"),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.


class User(AbstractUser):

    email = models.EmailField(unique=True)

    is_delegation = models.BooleanField('Delegation status', default=False)
    is_chair = models.BooleanField('Chair status', default=False)
    is_secretariat = models.BooleanField('Secretariat status', default=False)


class Delegation(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE)

    name = models.CharField(max_length=200, blank=True, null=True)
    size = models.IntegerField(default=0)
    contact_number = models.CharField(max_length=200, blank=True, null=True)

    def __str__(self):
        if self.name is not None:
            return self.name
        else:
            return f'Delegation Object: {self.user}'

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import User, Delegation
from django.contrib.auth import get_user_model

class UserCreationForm(UserCreationForm):

    class Meta(UserCreationForm):
        model = User
        fields = ('username', 'email', 'is_delegation', 'is_chair',
                  'is_secretariat', 'password1', 'password2')

class NewUserChangeForm(UserChangeForm):

    class Meta:

        model = User

        fields = ['email',
                  'first_name',
                  'last_name',
                  'password']

class DelegationSignUpForm(UserCreationForm):

    email = forms.EmailField(required=True)

    class Meta(UserCreationForm.Meta):

        model = User
        fields = ['username', 'email', 'password1', 'password2']

    def save(self, commit=True):
        user = super().save(commit=False)
        user.email = self.cleaned_data["email"]
        user.is_delegation = True
        if commit:
            user.save()
            delegation = Delegation.objects.create(user=user)
        return user

users/views.py
from django.shortcuts import render, redirect, HttpResponse
from django.contrib import messages
from django.contrib.auth import logout, authenticate, login
from django.contrib.auth.forms import AuthenticationForm
from .forms import DelegationSignUpForm, NewUserChangeForm

# Create your views here.
def home(request):

    TITLE = "MUN-Net"
    TENANT = request.tenant

    return render(
        request,
        "users/index.html",
        {"title":TITLE,
         "tenant": request.tenant}
    )

def register(request):

    TITLE = "Register"

    if request.method == "POST":
        form = DelegationSignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            username = form.cleaned_data.get('username')
            messages.success(
                request, f"You have successfully created a delegation account as: {username}")
            login(request, user)
            messages.info(request, f"You are now logged in as: {username}")
            return redirect("delegation:edit_delegation")
        else:
            for field in form:
                for error in field.errors:
                    messages.error(request, error)

            return render(request=request,
                          template_name="users/register.html",
                          context={"form": form,
                                   "title": TITLE,
                                   "tenant": request.tenant})

    form = DelegationSignUpForm
    return render(request,
                  "users/register.html",
                  {"form": form,
                   "title": TITLE,
                   "tenant": request.tenant}
                  )


def login_request(request):

    if request.method == "POST":
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.info(request, f"You are now logged in as {username}")
                return redirect("users:index")
            else:
                messages.error(request, "Invalid username or password")

        else:
            messages.error(request, "Invalid username or password")

    form = AuthenticationForm
    return render(request=request,
                  template_name="users/login.html",
                  context={"form": form,
                           "tenant": request.tenant}
                  )


def logout_request(request):

    logout(request)
    messages.info(request, "You have successfully logged out")
    return redirect("users:index")


def account(request):

    TITLE = "My Account"

    if request.method == "POST":
        form = NewUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            messages.info(request, "Account data saved")
            return redirect("users:index")
    else:
        form = NewUserChangeForm(instance=request.user)
        return render(request,
                      "users/account.html",
                      {"title": TITLE,
                      "form": form,
                      "tenant": request.tenant})


def index(request):

    if request.user.is_authenticated:
        if request.user.is_secretariat:
            return redirect("secretariat:index")
        if request.user.is_chair:
            return redirect('chair:index')
        if request.user.is_delegation:
            return redirect("delegation:index")

    return redirect('users:home')

users/templates/users/account.html
{% extends "header.html" %}

{% block content %}

  <form method="POST">
      {% csrf_token %}
      {{form.as_p}}
      <button type="submit" class="btn cyan darken-1">Save</button>
  </form>

{% endblock %}

users/templates/users/index.html
{% extends 'header.html' %}

{% block content %}

<div class="row">

  <div class="col s12 m12 l6">
    <div class="card red accent-4 hoverable">
      <div class="card-content white-text">
        <span class="card-title">Register as delegation</span>
      </div>
      <div class="card-action">
        <a href="{% url 'users:register' %}">Go</a>
      </div>
    </div>
  </div>

  <div class="col s12 m12 l6">
    <div class="card red accent-4 hoverable">
      <div class="card-content white-text">
        <span class="card-title">Login</span>
      </div>
      <div class="card-action">
        <a href="{% url 'users:login' %}">Go</a>
      </div>
    </div>
  </div>

</div>

{% endblock %}

users/templates/users/login.html
{% extends 'header.html' %}

{% block content %}

  <form method="POST">
      {% csrf_token %}
      {{form.as_p}}
      <button type="submit" class="btn cyan darken-1">Login</button>
  </form>
  If you don't have an account, <a href="/users/register" target="blank"><strong>register</strong></a> instead.

{% endblock %}

users/templates/users/register.html
{% extends 'header.html' %}

{% block content %}
  <p>
    Please ask your Head Delegate or Faculty Advisor to create an account for your delegation or school using this page, or sign up as an individual delegate
  </p>
  <form method="POST">
      {% csrf_token %}
      {{form.as_p}}
      <button type="submit" class="btn cyan darken-1">Register a Delegation Account</button>
  </form>
  If you already have an account <a href="{% url 'users:register' %}" target="blank"><strong>login</strong></a> instead.

{% endblock %}